### PR TITLE
porting from python2 to python3

### PR DESCRIPTION
**Pull request by chrispyduck**
Unit tests are all successful on python 2.7.8 and 3.4.2

### CODE REVIEW

**Comment by brendanwhitfield** [comment]
Thank you, I appreciate it

**Comment by chrispyduck** [comment]
It looks like I still have some work to do here... the Python 3 string changes caused some lower level issues that I didn't detect until I did a field test. Python 2 implementations shouldn't be affected, but the coverage gap in the included unit tests makes me think that some more extensive testing is warranted before this change is used in v2 production.

**Comment by brendanwhitfield** [comment]
Yup, shamefully, the tests are not by any means sufficient yet. I've always been performing field tests before releases, but I'd like to get it automated. Issue #4 has a link to an open source ECU/ELM327 simulator, but I haven't gotten around to it yet. That being said, this next release includes some fairly extensive changes, so I'd like to get that set up. If you ever get bored, I could certainly use the help.

**Comment by brendanwhitfield** [comment]
Yeah, this is ridiculous... I'm stopping current development until I get solid testing implemented. Sorry for the inconvenience.

**Comment by chrispyduck** [comment]
I completely understand that, and I should have done a field test before
the pull request... lazy me, I was hoping to avoid going out into the snow.
I'll take a look at the ELM simulator; if it meets my testing needs then
I'll see if I can incorporate it into both of our projects.

On Wed, Feb 18, 2015 at 2:17 AM, Brendan Whitfield <notifications@github.com

**Pull request merged**
